### PR TITLE
Find template paths via Musterman

### PR DESCRIPTION
**Pull request by ahx**
This adds support to find a path like "/pets/{id}" via `OasParser::Definition#path_by_path("/pets/1")`

### CODE REVIEW

**Comment by mheap** [comment]
@ahx Looks like we're missing a `Gemfile.lock` from this PR. Can you add it?

**Comment by ahx** [comment]
@mheap Fixed!

**Comment by mheap** [comment]
Released as `0.15.0` - thanks for the contribution

**Comment by ahx** [comment]
Hi @mheap, it looks like this PR is not part of `0.15.0` that is available on rubygems.org. Maybe something did go wrong with the release. But no hurries.

**Comment by mheap** [comment]
@ahx Ah, my mistake! `0.15.1` pushed

**Pull request merged**
